// ESLint flat config (P5-3).
// Install to use:  npm i -D eslint eslint-plugin-import  then:  npx eslint .
// Rules are tuned to the existing VOID style: single quotes, semicolons,
// browser globals, lenient formatting (Prettier owns formatting).
export default [
  {
    ignores: ['netlify/functions/**', 'node_modules/**', 'dist/**'],
  },
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        window: 'readonly',
        document: 'readonly',
        navigator: 'readonly',
        localStorage: 'readonly',
        fetch: 'readonly',
        console: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        IntersectionObserver: 'readonly',
        MutationObserver: 'readonly',
        matchMedia: 'readonly',
        addEventListener: 'readonly',
        removeEventListener: 'readonly',
        serviceWorker: 'readonly',
        FormData: 'readonly',
        Blob: 'readonly',
        URL: 'readonly',
        Promise: 'readonly',
        crypto: 'readonly',
        location: 'readonly',
        history: 'readonly',
        CustomEvent: 'readonly',
        customElements: 'readonly',
      },
    },
    rules: {
      semi: ['error', 'always'],
      quotes: ['error', 'single'],
      'no-unused-vars': ['warn', { args: 'none' }],
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-var': 'warn',
      'prefer-const': 'warn',
      eqeqeq: ['warn', 'smart'],
      curly: 'warn',
      'no-eval': 'error',
      'no-implied-eval': 'error',
      'no-new-func': 'error',
      'no-param-reassign': 'off',
      'no-console': 'off',
    },
  },
];
